# UGent 2016 textclass definition file.
# Base definitions for the UGent 2016 script layouts.
# Niko Strijbol <strijbol.niko@gmail.com>, 2019/04/29.

Style AcademyYear
	LabelString		"Academy year (academiejaar)"
	CopyStyle		Author
	LatexName		academyyear
End

Style Programme
	LabelString		"Programme (richting)"
	CopyStyle		Author
	LatexName		programme
End

Style WordCount
	LabelString		"Word count (aantal woorden)"
	CopyStyle		Author
	LatexName		wordcount
End

Style StudentNumber
	LabelString		"Student number (studentennummer)"
	CopyStyle		Author
	LatexName		studentnumber
End

Style Email
	LabelString		"E-mail"
	CopyStyle		Author
	LatexName		email
End

Style Phone
	LabelString		"Phone (telefoon)"
	CopyStyle		Author
	LatexName		phone
End

Style Address
	LabelString		"Address (adres)"
	CopyStyle		Author
	LatexName		address
End

Style Department
	LabelString		"Department (vakgroep)"
	CopyStyle		Author
	LatexName		department
End

Style ResearchGroup
	LabelString		"Research group (onderzoeksgroep)"
	CopyStyle		Author
	LatexName		researchgroup
End

Style Faculty
	LabelString		"Faculty-ish (faculteit)"
	CopyStyle		Author
	LatexName		facultisch
End

Style TitleText
	LabelString		"Title text (titeltekst)"
	CopyStyle		Author
	LatexName		titletext
End
